# This is a basic workflow to help you get started with Actions

name: Android Pull Request CI

on:
  pull_request:
    branches: [ main ]

jobs:
  #  test:
  #    runs-on: ubuntu-latest
  #
  #    steps:
  #      - name: Checkout the code
  #        uses: actions/checkout@v3
  #
  #      - name: set up JDK 17
  #        uses: actions/setup-java@v3
  #        with:
  #          distribution: 'corretto'
  #          java-version: '17'
  #
  #      - name: set up Android SDK
  #        uses: android-actions/setup-android@v2
  #
  #      - name: Grant execute permission for gradlew
  #        run: chmod +x gradlew
  #
  #      - name: Unit test
  #        run: ./gradlew testAll

  #     - name: Extract JacocoReport
  #        run: ./gradlew jacocoReport

  #     - name: log coverage on console
  #       run: ./gradlew jacocoTotalCoverage

  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Configure local.properties
        run: |
          echo SERVER_BASE_URL="${{ secrets.SERVER_BASE_URL }}" > local.properties
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Run detekt
        run: ./gradlew detekt

#  app-build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout the code
#        uses: actions/checkout@v3
#
#      - name: set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'corretto'
#          java-version: '17'
#
#      - name: set up Android SDK
#        uses: android-actions/setup-android@v2
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Run build
#        run: ./gradlew app:assembleDevRelease
